runtime: nodejs
env: flex
service: default

runtime_config:
  operating_system: ubuntu22

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

env_variables:
  NODE_ENV: "production"

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Pass in keys
includes:
  - .env.yaml
