runtime: nodejs22
service: default
instance_class: F2

# Use automatic scaling for production
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

# Set up health checks
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

entrypoint: npm run build && npm run start:main

handlers:
  - url: /.*
    script: auto
    secure: always  # Force HTTPS
